# -- 主菜单（顶栏）--

[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "分类"
  pageRef = "categories"
  weight = 30

[[main]]
  name = "系列"
  pageRef = "series"
  weight = 40

[[main]]
  name = "归档"
  pageRef = "archives"
  weight = 50

[[main]]
  name = "关于"
  pageRef = "about"
  weight = 60